Overhaul overload semantics, remove erasure, add union math
This pull request:

1.  Modifies how mypy handles overloads to match the proposal
    I made in the typing repo.

2.  Starts removing type erasure from overload checks.

3.  Adds support for basic union math.

4.  Makes overloads respect keyword-only args

This pull request does NOT implement the following:

1.  Special-casing descriptors

2.  Improving how operator methods are handled: I've tweaked one or two
    methods to take advantage of some of the changes I made in this PR,
    but stayed away from making any drastic changes for now.

3.  Detecting partially overlapping argument types -- e.g. code like:

        @overload
        def f(x: Union[A, B]) -> str: ...
        @overload
        def f(x: Union[B, C]) -> int: ...

        @overload
        def g(x: Tuple[int, ...]) -> str: ...
        @overload
        def g(x: Tuple[int, int]) -> int: ...

4.  Detecting overlapping "argument counts". For example, we should
    flag the following as an error since the first alternative could
    potentially overlap with the second.

        @overload
        def f(*args: int) -> int: ...
        @overload
        def f(x: int, y: int, z: int) -> str: ...

5.  The "is-more-precise" relation. It's working in most normal cases
    but still contains a few bugs, mostly relating to type vars.
    For example, this currently isn't being flagged as an error:

        class Wrapper(Generic[T]):
            @overload
            def f(self, x: int) -> int: ...  # No error?
            @overload
            def f(self, x: T) -> str: ...

    (This PR does the right thing if 'T' isn't bound to a containing
    class though:)

        class Wrapper:
            @overload
            def f(self, x: int, y: int) -> int: ...  # Error
            @overload
            def f(self, x: T, y: T) -> str: ...

    Currently, what I'm doing is using the existing `is_more_precise`
    method, which calls `is_proper_subtype`. I think i'll either need to
    rewrite `is_more_precise` to do what I want with typevars or find a
    way of forcing the two methods to unify their typevars before running
    the `is_proper_subtype` check.

The plan is to address these 5 TODOs in future pull requests. Items 1
and 2 are basically orthogonal to the overloads overhaul; items 3, 4,
and 5 basically boil down to finding ways to teach mypy to detect if one
thing is *potentially* compatible with another.

For example, mypy contains code to tell if one type is *definitely* a
subtype of another; fixing items 3 and 5 involve writing code to check
if a type is *potentially* a subtype of another.