Expand TypeVarTuple default (PEP 696) (#16851)
Small change to fix an error when expanding a TypeVarTuple default.

```
RuntimeError: Invalid type replacement to expand: Unpack[tuple[builtins.int, builtins.str]]
```

Ref: #14851