Send early errors to workers (#20822)
Ref https://github.com/python/mypy/issues/933

When parallel parsing is ready, we will not run `load_graph()` in each
worker. So, we need to send early errors (mostly import errors) to the
relevant workers. Couple notes here:
* Now `only_once` messages are shown only once per worker. It is hard to
fix, and I don't think we should really bother. It doesn't affect
correctness, and may only slightly increase noise. Btw they were never
truly `only_once`, when reading errors from cache we can get multiple
occurrences of the same error/note.
* While I am at it, I switch few more error to the standard `file.py:
error: some message` format.