Fix detecting missing parameter/return type annotations with fast parser
Some test code:

    # test.py
    def f1(i) -> None:
        pass

    def f2(i: int):
        pass

    def f3():
        pass

Without fast parser the detection was working just fine:

    % mypy --disallow-untyped-defs test.py
    test.py: note: In function "f1":
    test.py:1: error: Function is missing a type annotation for one or more arguments
    test.py: note: In function "f2":
    test.py:5: error: Function is missing a return type annotation
    test.py: note: In function "f3":
    test.py:9: error: Function is missing a type annotation

With fast parser, however, functions missing only parameter or only
return type annotation would remain undetected:

    % mypy --disallow-untyped-defs --fast-parser test.py
    test.py: note: In function "f3":
    test.py:9: error: Function is missing a type annotation