Allow disabling extra flags with MYPYC_NO_EXTRA_FLAGS env variable (#20507)
We need a way to disable these when cross compiling as these flags will
break due to picking up the host rather than the target.

Should fix:
```
/home/buildroot/buildroot/output/per-package/python-librt/host/bin/aarch64-linux-gcc -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g0 -D_FORTIFY_SOURCE=1 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -fPIC -I. -Ibase64 -I/home/buildroot/buildroot/output/build/python3-3.13.11/Include -I/home/buildroot/buildroot/output/build/python3-3.13.11 -c base64/arch/avx/codec.c -o build/temp.linux-aarch64-cpython-313/base64/arch/avx/codec.o -O3 -Wno-unused-function -mavx
aarch64-linux-gcc.br_real: error: unrecognized command-line option ‘-mavx’
error: command '/home/buildroot/buildroot/output/per-package/python-librt/host/bin/aarch64-linux-gcc' failed with exit code 1
```