Fix missing type (but why?!)
(Meant more to ask a question than to be merged, for now.)

This fixes the following type error when mypy is run against its
own implementation:

```
mypy/checker.py:10: note: In module imported here:
mypy/nodes.py: note: In member "set_line" of class "Node":
mypy/nodes.py:95: error: Cannot determine type of 'line'
```

I don't actually understand why this is necessary, though!
Based on http://mypy.readthedocs.org/en/latest/class_basics.html ,
it seems like the initialization `self.line = 0` in the class's
`__init__` ought to do the job.  What am I missing?