Run build a second time when using --install-types --non-interactive  (#10669)
If the first build finds missing stub packages, run the build a second
time after installing types. Only show errors from the final build.

Example output:
```
$ mypy --install-types --non-interactive t.py
Installing missing stub packages:
/Users/jukka/venv/mypy/bin/python3 -m pip install types-redis

Collecting types-redis
  Using cached types_redis-3.5.2-py2.py3-none-any.whl (11 kB)
Installing collected packages: types-redis
Successfully installed types-redis-3.5.2

t.py:2: error: Unsupported operand types for + ("int" and "str")
Found 1 error in 1 file (checked 1 source file)
```

Work on #10600.