Fix `gen_is_coroutine` for Python 3.13 (#17501)
The `_PyInterpreterFrame` struct was changed in
https://github.com/python/cpython/pull/105727 to store the code object
in `f_executable` instead of `f_code`.

Fixes
```cpp
  /home/runner/work/mypy/mypy/mypyc/lib-rt/pythonsupport.h: In function ‘_PyGen_GetCode’: (diff)
  /home/runner/work/mypy/mypy/mypyc/lib-rt/pythonsupport.h:403:17: error: ‘_PyInterpreterFrame’ has no member named ‘f_code’ (diff)
    403 |     return frame->f_code; (diff)
        |                 ^~ (diff)
```