Improve verbose formatting to disambiguate types of the same name.
Previously, foo.Bar and baz.Bar would both be formatted as "Bar" in
error messages, which causes confusing errors like the following:

error: Argument 2 to "quux" has incompatible type "Bar"; expected "Bar"