Always use `.enum_members` to find enum members (#18675)
Closes #18565 

This fixes the problem with `nonmember` and `member` special cases,
however, it required me to change one test case.

See `testEnumReachabilityPEP484ExampleSingletonWithMethod` change,
because in runtime `token` is not a member by default, at least in
recent python versions. Proof:

```python
# 3.14
>>> from enum import Enum
>>> class Empty(Enum):
...     token = lambda x: x
...     
>>> Empty.token
<function Empty.<lambda> at 0x101251250>
>>> Empty.token.value
```

and

```python
# 3.11
>>> from enum import Enum
>>> class Empty(Enum):
...     token = lambda x: x
... 
>>> Empty.token
<function Empty.<lambda> at 0x104757600>
>>> Empty.token.value
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'function' object has no attribute 'value'
```

So, I had to add `member()` there to make the test pass.