Syntax error messages capitalization (#19114)
Fixes #https://github.com/python/mypy/issues/19107

Cause of Issue:
```ast3``` parser raises exception with error message which sometimes non-standardized.

eg :
```
error: expected an indented block after function definition on line 1
[syntax]
```

Resolution:
- standardize the exception error message before report generation for syntax exceptions specifically
 
Contributors:
- Me and [@aman
](https://github.com/amansomething)

---------

Co-authored-by: Charulata Lodha <clodha@bloomberg.net>
Co-authored-by: amansomething <amansomething@users.noreply.github.com>