Use standard formatting for note on unexpected keyword (#20808)
Closes https://github.com/python/mypy/issues/4773
Closes https://github.com/python/mypy/issues/10480
Closes https://github.com/python/mypy/issues/20640

Currently this is the only message that uses this non-standard
formatting, while:
* Some users find it confusing
* We need ~400 lines of code to support this special case
* It still has bugs that will require even more special-casing in
various places to fix them.

So here I implement a minimal change I propose in
https://github.com/python/mypy/issues/4773, namely use this (standard)
format:
```
main.py:5: error: Unexpected keyword argument "location" for "method" of "Class"
main.py:5: note: "method" defined in "pkg.mod"
```
if the function is defined in a different module.

If we want to, we can add extra info (like available argument names with
same type), as well as start using this note in more places in separate
PRs.