experiment with removing v = None
This attempts to get at mypy/config_parser.py:620: error: Incompatible types in assignment (expression has type tuple[int, int], variable has type Optional[bool])  [assignment]

however, I think this leaves v undefined in the else path, which is bad